name: Build and Test on DEV

on:
  push:
    branches: [ DEV ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up node js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Build project
        run: npm run build --if-present

      - name: Debug – List root folder contents
        run: dir

      - name: Debug – List .next folder contents
        run: dir .next

      - name: Debug — Print current directory
        run: pwd

      - name: Zip .next folder (Windows compatible)
        run: Compress-Archive -Path .next -DestinationPath next-build.zip
        shell: pwsh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: next-build.zip

